version: "3.9"

networks:
  default:
    external:
      name: traefik

volumes:
  grafana-storage:
  prometheus-storage:

x-restart-policy:  &restart-policy
  restart: unless-stopped

services:
  grafana:
    <<: *restart-policy
    image: grafana/grafana:9.3.1
    container_name: ${DEPLOY_PATH}_grafana
    env_file: .env
    depends_on: 
      - loki
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/monitoring.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.subdomain=${DEPLOY_PATH}"
      - "traefik.http.services.${DEPLOY_PATH}.loadbalancer.server.port=3000"
      - "traefik.http.routers.${DEPLOY_PATH}.tls.certresolver=letsEncrypt"

  prometheus:
    <<: *restart-policy
    image: prom/prometheus
    container_name: ${DEPLOY_PATH}_prometheus
    depends_on: 
      - node-exporter
      - cadvisor
      - promtail
    volumes:
      - prometheus-storage:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --enable-feature=expand-external-labels
      - --storage.tsdb.retention.time=7d
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    expose:
      - 9090

  node-exporter:
    <<: *restart-policy
    image: prom/node-exporter
    container_name: ${DEPLOY_PATH}_nodeExporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100

  cadvisor:
    <<: *restart-policy
    image: gcr.io/cadvisor/cadvisor
    container_name: ${DEPLOY_PATH}_cAdvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080

  loki:
    image: grafana/loki:2.6.1
    container_name: ${DEPLOY_PATH}_loki
    volumes:
      - ./loki.yml:/etc/loki/local-config.yml
    command:
      - --config.file=/etc/loki/local-config.yml
      - --ruler.storage.type=local
      - --ruler.storage.local.directory=/tmp/loki/rules
    expose:
      - 3100
    labels:
      - "traefik.enable=true"
      - "traefik.subdomain=loki"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
      - "traefik.http.routers.loki.tls.certresolver=letsEncrypt"

  promtail:
    <<: *restart-policy
    image: grafana/promtail:2.6.1
    container_name: ${DEPLOY_PATH}_promtail
    env_file: .env
    depends_on: 
      - loki
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: 
      - --config.file=/etc/promtail/promtail-config.yaml
      - -config.expand-env=true
      - -print-config-stderr
    expose:
      - 9080
