server:
  http_listen_address: 127.0.0.1
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml
  sync_period: 10s

client:
  url: http://loki:3100/loki/api/v1/push
  external_labels:
    server: v2
    environment: production
  backoff_config:
    max_period: 10m
    max_retries: 10
    min_period: 1s

scrape_configs:
  - job_name: docker-container-logs

    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
    
    relabel_configs:
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        regex: '(.*)'
        target_label: '${PREFIX}_compose_project'

      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: '${PREFIX}_container_name'

      - source_labels: ['__meta_docker_network_name']
        regex: '(.*)'
        target_label: '${PREFIX}_container_network'
    
    pipeline_stages:
      - json:
          expressions:
            timestamp:
      - timestamp:
          source: timestamp
          format: RFC1123
          location: Europe/Moscow
      - drop:
          older_than: 168h
