global:
  scrape_interval: 30s 
  external_labels:
    hostname: $HOSTNAME

scrape_configs:
  - job_name: traefik
    static_configs:
      - targets: 
        - traefik:8082

  - job_name: containers
    static_configs:
    - targets: 
      - cadvisor:8080

  - job_name: hardware
    static_configs:
      - targets: 
        - node-exporter:9100
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: 'node-exporter(:.*)?'
        replacement: 'main_node'

  - job_name: promtail
    static_configs:
      - targets: 
        - promtail:9080
  
  - job_name: loki
    static_configs:
      - targets:
          - loki:3100
